-- Enable necessary extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Create Enums
CREATE TYPE user_role AS ENUM ('admin', 'pengurus', 'anggota');
CREATE TYPE simpanan_jenis AS ENUM ('setor', 'tarik');
CREATE TYPE pinjaman_status AS ENUM ('pengajuan', 'disetujui', 'cair', 'lunas', 'ditolak');
CREATE TYPE angsuran_status AS ENUM ('belum', 'lunas', 'telat');
CREATE TYPE pengaturan_tipe AS ENUM ('nominal', 'persen', 'enum', 'integer');

-- 2. User Roles Profile Table
CREATE TABLE public.user_roles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    role user_role NOT NULL DEFAULT 'anggota',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Pengaturan Table
CREATE TABLE public.pengaturan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kunci VARCHAR(100) UNIQUE NOT NULL,
    nilai DECIMAL(15, 2) NOT NULL,
    tipe pengaturan_tipe DEFAULT 'nominal'::pengaturan_tipe,
    keterangan VARCHAR(255),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Anggota Table
CREATE TABLE public.anggota (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    nik VARCHAR(16) UNIQUE NOT NULL,
    nama VARCHAR(150) NOT NULL,
    alamat TEXT,
    telepon VARCHAR(20),
    tanggal_gabung DATE NOT NULL DEFAULT CURRENT_DATE,
    status VARCHAR(20) DEFAULT 'aktif' CHECK (status IN ('aktif', 'keluar')),
    tanggal_keluar DATE,
    keterangan_keluar TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Kategori Pinjaman Table
CREATE TABLE public.kategori_pinjaman (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_kategori VARCHAR(100) UNIQUE NOT NULL,
    bunga_persen DECIMAL(5, 2) NOT NULL,
    keterangan VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Simpanan Tables
CREATE TABLE public.simpanan_pokok (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anggota_id BIGINT REFERENCES public.anggota(id) ON DELETE CASCADE NOT NULL,
    jumlah DECIMAL(15, 2) NOT NULL,
    tanggal_bayar DATE NOT NULL DEFAULT CURRENT_DATE,
    keterangan VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE public.simpanan_wajib (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anggota_id BIGINT REFERENCES public.anggota(id) ON DELETE CASCADE NOT NULL,
    bulan SMALLINT NOT NULL CHECK (bulan BETWEEN 1 AND 12),
    tahun SMALLINT NOT NULL,
    jumlah DECIMAL(15, 2) NOT NULL,
    tanggal_bayar DATE NOT NULL DEFAULT CURRENT_DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT uq_wajib_anggota_bulan_tahun UNIQUE (anggota_id, bulan, tahun)
);

CREATE TABLE public.simpanan_sukarela (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anggota_id BIGINT REFERENCES public.anggota(id) ON DELETE CASCADE NOT NULL,
    jenis simpanan_jenis NOT NULL,
    jumlah DECIMAL(15, 2) NOT NULL,
    saldo_setelah DECIMAL(15, 2) NOT NULL,
    tanggal DATE NOT NULL DEFAULT CURRENT_DATE,
    keterangan VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. Pinjaman Table
CREATE TABLE public.pinjaman (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anggota_id BIGINT REFERENCES public.anggota(id) ON DELETE CASCADE NOT NULL,
    kategori_id BIGINT REFERENCES public.kategori_pinjaman(id) NOT NULL,
    penjamin_anggota_id BIGINT REFERENCES public.anggota(id) ON DELETE SET NULL,
    jumlah_pinjaman DECIMAL(15, 2) NOT NULL,
    tenor_bulan SMALLINT NOT NULL CHECK (tenor_bulan > 0),
    bunga_persen DECIMAL(5, 2) NOT NULL,
    angsuran_pokok DECIMAL(15, 2) NOT NULL,
    angsuran_bunga DECIMAL(15, 2) NOT NULL,
    total_angsuran DECIMAL(15, 2) NOT NULL,
    tujuan_pinjaman TEXT,
    status pinjaman_status DEFAULT 'pengajuan'::pinjaman_status,
    disetujui_oleh UUID REFERENCES auth.users(id),
    tanggal_pengajuan DATE NOT NULL DEFAULT CURRENT_DATE,
    tanggal_disetujui DATE,
    tanggal_cair DATE,
    tanggal_lunas DATE,
    catatan_penolakan TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. Angsuran Table
CREATE TABLE public.angsuran (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinjaman_id BIGINT REFERENCES public.pinjaman(id) ON DELETE CASCADE NOT NULL,
    ke SMALLINT NOT NULL CHECK (ke > 0),
    tanggal_jatuh_tempo DATE NOT NULL,
    tanggal_bayar DATE,
    pokok DECIMAL(15, 2) NOT NULL,
    bunga DECIMAL(15, 2) NOT NULL,
    denda DECIMAL(15, 2) DEFAULT 0.00 NOT NULL,
    total_bayar DECIMAL(15, 2),
    status angsuran_status DEFAULT 'belum'::angsuran_status,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 9. Denda Table
CREATE TABLE public.denda (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    angsuran_id BIGINT REFERENCES public.angsuran(id) ON DELETE CASCADE NOT NULL,
    jumlah DECIMAL(15, 2) NOT NULL,
    hari_telat INTEGER DEFAULT 0 NOT NULL,
    tanggal_hitung DATE NOT NULL DEFAULT CURRENT_DATE,
    keterangan VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
